version: "3.9"
services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: {}
